<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Commando</string>
  <key>comment</key>
  <string>Commando Syntax: version 1.0</string>
  <key>fileTypes</key>
  <array>
    <string>do</string>
  </array>
  <key>foldingStartMarker</key>
  <string>^\s*(script|layer|if|each-(?:data|data-n|in-map|in-group))(?=\s|$)</string>
  <key>foldingStopMarker</key>
  <string>^\s*end(?=\s|$)</string>
  <key>keyEquivalent</key>
  <string>^~S</string>

  <key>repository</key>
  <dict>

    <key>single_quoted_string</key>
    <dict>
      <key>begin</key>
      <string>(?&lt;=\s|=|,)'</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.commando</string>
        </dict>
      </dict>
      <key>end</key>
      <string>'</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.commando</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.quoted.single.commando</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>constant.character.escape.commando</string>
        </dict>
      </array>
    </dict>

    <key>double_quoted_string</key>
    <dict>
      <key>begin</key>
      <string>(?&lt;=\s|=|,)"</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.commando</string>
        </dict>
      </dict>
      <key>end</key>
      <string>"</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.commando</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.quoted.double.commando</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>constant.character.escape.commando</string>
        </dict>
      </array>
    </dict>

    <key>numeric_constant</key>
    <dict>
      <key>match</key>
      <string>(?&lt;=\s|=|,)0x[a-fA-F\d]+|(?&lt;=\s|=|,)-?\d+(\.\d+)?([eE]-?\d+)?|(?&lt;=\s|=|,)-?\.\d+([eE]-?\d+)?</string>
      <key>name</key>
      <string>constant.numeric.commando</string>
    </dict>

    <key>operator_symbol</key>
    <dict>
      <key>match</key>
      <string>\+|(?&lt;=\s|=|,)-(?!\d)|=|,|(?&lt;!\.)\.(?!\.)|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
      <key>name</key>
      <string>keyword.operator.commando</string>
    </dict>

    <key>argument_name</key>
    <dict>
      <key>name</key>
      <string>meta.parameter.name.commando</string>
      <key>comment</key>
      <string>argument name within a command</string>
      <key>match</key>
      <string>(?&lt;=(\s|=|,))([@$A-Za-z][A-Za-z0-9-]*)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.commando</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.commando</string>
        </dict>
      </dict>
    </dict>

  </dict>

  <key>patterns</key>
  <array>

    <dict>
      <key>name</key>
      <string>meta.keyword.continuation.commando</string>
      <key>begin</key>
      <string>^\s*(-)(?=\s+[-"'0-9({@$A-Za-z])</string>
      <key>end</key>
      <string>(?:(?&lt;=\s)(is|do)\s*)?(?:$|(?=--))</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.command.commando</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.block.commando</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#single_quoted_string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#double_quoted_string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric_constant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operator_symbol</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#argument_name</string>
        </dict>
      </array>
    </dict>

    <dict>
      <key>name</key>
      <string>meta.keyword.command.commando</string>
      <key>begin</key>
      <string>^\s*([@A-Za-z][@A-Za-z0-9.-]*)\s*((?&lt;=\s)(?!(?:is|do)\s*(?:$|--))[@$A-Za-z][@$A-Za-z0-9.-]*(?=\s|$))?</string>
      <key>end</key>
      <string>(?:(?&lt;=\s)(is|do)\s*)?(?:$|(?=--))</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.command.commando</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.function.commando</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.block.commando</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#single_quoted_string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#double_quoted_string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric_constant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operator_symbol</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#argument_name</string>
        </dict>
      </array>
    </dict>

    <dict>
      <key>name</key>
      <string>comment.line.double-dash.commando</string>
      <key>match</key>
      <string>(--.*)$</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.commando</string>
        </dict>
      </dict>
    </dict>

  </array>
  <key>scopeName</key>
  <string>source.commando</string>
  <key>uuid</key>
  <string>F23DB5B2-7D08-11D9-A709-000D93B6E43C</string>
</dict>
</plist>
